export default {
  FETCH_REPOSITORIES_START: 'FETCH_REPOSITORIES_START',
  FETCH_REPOSITORIES_SUCCESS: 'FETCH_REPOSITORIES_SUCCESS',
  FETCH_REPOSITORIES_FAILURE: 'FETCH_REPOSITORIES_FAILURE',
  CLEAR_REPOSITORIES: 'CLEAR_REPOSITORIES'
};
